#ifndef GAMEPLAY_DIFFICULTY_H
#define GAMEPLAY_DIFFICULTY_H

typedef enum {
    GAMEPLAY_DIFFICULTY_MEDIUM = 0,
    GAMEPLAY_DIFFICULTY_EASY = 1,
    GAMEPLAY_DIFFICULTY_HARD = 2,
    GAMEPLAY_DIFFICULTY_HELENA = 3
} GameplayDifficulty;

#endif
